### ISSUE TITLE
KAWW 3.1 - Bug: When using stairs buttons, you will shoot

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#91]
1. Be Antitank with loaded missile.
2. Go to stairs
3. Click on a button (up or down).
4. You will travel up or down but also shoot at the wall.

If you don't have Lucky Perk, you will die.
This shouldn't happen.

The bug can be seen in this video. https://www.youtube.com/watch?v=s_Lmj695ZG8

Please either restore stairs buttons to how it was before (round buttons) or disable shooting when clicking on the rectangle buttons.

**Comment by NoahTheLegend** [comment]
use another mouse button

**Comment by mugg91** [comment]
The issue is still present.

**Comment by mugg91** [comment]
> use another mouse button

Left mouse key is the only one that will let me travel stairs via pressing on a button.

**Comment by NoahTheLegend** [comment]
according to https://github.com/NoahTheLegend/kaww/issues/69#issuecomment-1904823993 - i decided not to disable controls due to unnecessary tons of code, kag does not provide reliable ways to take keys input without "hacking" through engine functions and methods, which would lead to a requirement of more code for fixing new misbehaviour
